### ISSUE TITLE
Keith Shadis sound files?

### ISSUE THREAD

**Issue by BennyHernandez** [JonSnowWhite/discord-soundboard-bot#13]
idk

**Comment by JonSnowWhite** [comment]
https://drive.google.com/drive/folders/1UF6QsXgnj1fwUUgaG24IEIf6jQeLgdmz?usp=sharing @BennyFaelz 
I changed some of the files names but they mostly stayed the same. Please comment whether I messed up the access rights in docs, so I can close the issue or solve that.

**Comment by BennyHernandez** [comment]
Look good to me. Thank you!!
